options:
  logging: CLOUD_LOGGING_ONLY

volumes:
  - name: kube
    path: /kube

steps:
- id: prepare-env
  name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
    - -euxc
    - |
      PROJECT_ID="${PROJECT_ID}"
      TFSTATE_BUCKET="vikunja-case-tfstate"
      echo "Checking bucket: gs://${TFSTATE_BUCKET}"
      gsutil ls -b "gs://${TFSTATE_BUCKET}" >/dev/null
      cat > /workspace/env.sh <<'EOF'
      export REGION="europe-west4"
      export CLUSTER_NAME="vikunja-autopilot"
      export TFSTATE_BUCKET="vikunja-case-tfstate"
      export PROJECT_ID="${PROJECT_ID}"
      export KUBECONFIG="/kube/config"
      EOF

- id: terraform-apply
  name: hashicorp/terraform:1.9.6
  entrypoint: sh
  args:
    - -euxc
    - |
      . /workspace/env.sh
      cd infra/terraform
      terraform init \
        -backend-config="bucket=${TFSTATE_BUCKET}" \
        -backend-config="prefix=${PROJECT_ID}/state"
      terraform apply -auto-approve

- id: k8s-setup
  name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
    - -euxc
    - |
      . /workspace/env.sh
      export KUBECONFIG="${KUBECONFIG}"
      gcloud container clusters get-credentials "${CLUSTER_NAME}" --region "${REGION}" --project "${PROJECT_ID}"

      kubectl get ns vikunja >/dev/null 2>&1 || kubectl create ns vikunja
      kubectl label ns vikunja app.kubernetes.io/managed-by=Helm --overwrite
      kubectl annotate ns vikunja meta.helm.sh/release-name=vikunja --overwrite
      kubectl annotate ns vikunja meta.helm.sh/release-namespace=vikunja --overwrite

      DB_PASS="$(gcloud secrets versions access latest --secret=vikunja-db-password --project "${PROJECT_ID}")"
      kubectl -n vikunja create secret generic vikunja-db-secret \
        --from-literal=VIKUNJA_DATABASE_PASSWORD="${DB_PASS}" \
        --dry-run=client -o yaml | kubectl apply -f -
  volumes:
    - name: kube
      path: /kube

- id: helm-deploy
  name: alpine/helm:3.14.4
  entrypoint: sh
  args:
    - -euxc
    - |
      export KUBECONFIG=/kube/config
      helm repo add vikunja https://vikunja.github.io/helm-charts || true
      helm repo update
      helm upgrade --install vikunja vikunja/vikunja \
        --namespace vikunja --create-namespace
  volumes:
    - name: kube
      path: /kube
