steps:
  - name: gcr.io/cloud-builders/gcloud
    id: get-creds + prep namespace
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        CLUSTER_NAME="vikunja-autopilot"
        REGION="europe-west4"

        # Get kubeconfig for the cluster
        gcloud container clusters get-credentials "$CLUSTER_NAME" --region "$REGION"

        # Persist kubeconfig so the next step can use it
        export KUBECONFIG=/workspace/kubeconfig
        kubectl config view --raw > "$KUBECONFIG"

        # Ensure namespace exists and is Helm-adoptable
        kubectl get ns vikunja >/dev/null 2>&1 || kubectl create ns vikunja
        kubectl label ns vikunja app.kubernetes.io/managed-by=Helm --overwrite
        kubectl annotate ns vikunja meta.helm.sh/release-name=vikunja --overwrite
        kubectl annotate ns vikunja meta.helm.sh/release-namespace=vikunja --overwrite

  # Pin a working Helm image (avoid ':latest' not found)
  - name: alpine/helm:3.14.4
    id: helm upgrade/install
    env:
      - KUBECONFIG=/workspace/kubeconfig
    args:
      - upgrade
      - --install
      - vikunja
      - ./helm/vikunja
      - --namespace
      - vikunja
      - --create-namespace

options:
  # If your trigger specifies a service account, this avoids requiring a logs bucket.
  logging: CLOUD_LOGGING_ONLY
