# cloudbuild.yaml
options:
  logging: CLOUD_LOGGING_ONLY  # compatible even if your trigger sets a service account

steps:
# 0) Get cluster credentials
- id: get-credentials
  name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
    - -ceu
    - |
      gcloud container clusters get-credentials vikunja-autopilot \
        --region europe-west4 \
        --project vikunja-case

# 1) Ensure namespace exists and is Helm-adoptable
- id: prepare-namespace
  name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
    - -ceu
    - |
      kubectl get ns vikunja >/dev/null 2>&1 || kubectl create ns vikunja
      kubectl label ns vikunja app.kubernetes.io/managed-by=Helm --overwrite
      kubectl annotate ns vikunja meta.helm.sh/release-name=vikunja meta.helm.sh/release-namespace=vikunja --overwrite

# 2) Create/refresh DB secret from Secret Manager (no custom $VARs used)
- id: create-secrets
  name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
    - -ceu
    - |
      kubectl -n vikunja create secret generic vikunja-db-secret \
        --from-literal=postgresql-password="$(gcloud secrets versions access latest --secret=vikunja-db-password)" \
        --dry-run=client -o yaml | kubectl apply -f -

# 3) Helm upgrade/install (chart lives at ./helm/vikunja)
- id: helm-deploy
  name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
    - -ceu
    - |
      helm version
      helm upgrade --install vikunja ./helm/vikunja \
        --namespace vikunja --create-namespace \
        --wait --timeout 10m
