# cloudbuild.yaml — deploy only, no custom substitutions required
timeout: "3600s"

options:
  # Required when the trigger runs with a Service Account
  logging: CLOUD_LOGGING_ONLY

steps:
  # 1) Fetch kubeconfig for the existing cluster and prep the namespace
  - name: gcr.io/cloud-builders/gcloud
    id: kubeconfig-and-namespace
    env: ["HOME=/workspace"]   # share kubeconfig via /workspace (no 'volumes' field)
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail

        # <<< EDIT THESE TWO IF YOUR CLUSTER NAME / REGION DIFFER >>>
        CLUSTER_NAME="vikunja-autopilot"
        REGION="europe-west4"
        # ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

        echo "Using cluster: ${CLUSTER_NAME} in region: ${REGION}, project: ${PROJECT_ID}"
        gcloud container clusters get-credentials "${CLUSTER_NAME}" --region "${REGION}" --project "${PROJECT_ID}"

        # Make namespace Helm-adoptable to avoid the ownership error you saw earlier
        kubectl get ns vikunja >/dev/null 2>&1 || kubectl create namespace vikunja
        kubectl label namespace vikunja app.kubernetes.io/managed-by=Helm --overwrite
        kubectl annotate namespace vikunja meta.helm.sh/release-name=vikunja --overwrite
        kubectl annotate namespace vikunja meta.helm.sh/release-namespace=vikunja --overwrite

  # 2) Ensure required secrets (pull DB password from Secret Manager if present)
  - name: gcr.io/cloud-builders/gcloud
    id: ensure-secrets
    env: ["HOME=/workspace"]
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail

        # Try to read DB password from Secret Manager
        set +e
        DB_PW="$(gcloud secrets versions access latest --secret vikunja-db-password 2>/dev/null)"
        set -e
        if [ -n "${DB_PW}" ]; then
          kubectl -n vikunja create secret generic vikunja-db-secret \
            --dry-run=client -o yaml \
            --from-literal=POSTGRES_DB=vikunja \
            --from-literal=POSTGRES_USER=vikunja \
            --from-literal=POSTGRES_PASSWORD="${DB_PW}" | kubectl apply -f -
        else
          echo "WARNING: Secret Manager secret 'vikunja-db-password' not found; skipping DB secret creation."
        fi

        # App secret (JWT) — only create if missing
        if ! kubectl -n vikunja get secret vikunja-app-secret >/dev/null 2>&1 ; then
          APP_SECRET="$(head -c 48 /dev/urandom | base64 | tr -dc 'A-Za-z0-9' | head -c 32)"
          kubectl -n vikunja create secret generic vikunja-app-secret \
            --from-literal=VIKUNJA_SERVICE_JWTSECRET="${APP_SECRET}"
        fi

  # 3) Helm deploy from the repo's chart folder
  - name: alpine/helm:3.14.4
    id: helm-upgrade
    env: ["HOME=/workspace"]
    entrypoint: sh
    args:
      - -c
      - |
        set -euo pipefail
        CHART="./helm"   # adjust if your chart is elsewhere (e.g., ./infra/helm)

        if [ ! -d "$CHART" ]; then
          echo "Chart directory '$CHART' not found in the repo. Commit your Helm chart under ./helm/ or update CHART path."; exit 1
        fi

        helm version
        helm upgrade --install vikunja "$CHART" \
          --namespace vikunja \
          --create-namespace \
          --wait \
          --timeout 15m
