options:
  logging: CLOUD_LOGGING_ONLY

steps:
# 0) Get cluster credentials (writes kubeconfig to /builder/home/.kube/config)
- id: get-credentials
  name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
    - -ceu
    - |
      gcloud container clusters get-credentials vikunja-autopilot \
        --region europe-west4 \
        --project vikunja-case

# 1) Prepare namespace and make it Helm-adoptable
- id: prepare-namespace
  name: gcr.io/cloud-builders/gcloud
  env:
    - KUBECONFIG=/builder/home/.kube/config
  entrypoint: bash
  args:
    - -ceu
    - |
      kubectl get ns vikunja >/dev/null 2>&1 || kubectl create ns vikunja
      kubectl label ns vikunja app.kubernetes.io/managed-by=Helm --overwrite
      kubectl annotate ns vikunja meta.helm.sh/release-name=vikunja meta.helm.sh/release-namespace=vikunja --overwrite

# 2) Create/Update DB secret from Secret Manager
- id: create-secrets
  name: gcr.io/cloud-builders/gcloud
  env:
    - KUBECONFIG=/builder/home/.kube/config
  entrypoint: bash
  args:
    - -ceu
    - |
      kubectl -n vikunja create secret generic vikunja-db-secret \
        --from-literal=postgresql-password="$(gcloud secrets versions access latest --secret=vikunja-db-password)" \
        --dry-run=client -o yaml | kubectl apply -f -

# 3) Helm deploy using official Helm image (pin version!)
- id: helm-deploy
  name: ghcr.io/helm/helm:v3.14.4
  env:
    - KUBECONFIG=/builder/home/.kube/config
  entrypoint: sh
  args:
    - -ceu
    - |
      helm version
      # Make sure your chart exists at ./helm/vikunja in the repo
      helm upgrade --install vikunja ./helm/vikunja \
        --namespace vikunja --create-namespace \
        --wait --timeout 10m
