timeout: "3600s"

options:
  # If your trigger uses a custom service account, this satisfies the logging requirement
  logging: CLOUD_LOGGING_ONLY

steps:
  # 0) Terraform: create/keep infra and write outputs for step 1
  - name: hashicorp/terraform:1.9.6
    id: terraform-apply-and-outputs
    entrypoint: sh
    args:
      - -c
      - >
        set -eu;
        terraform init -input=false &&
        terraform apply -auto-approve -input=false &&
        REGION=europe-west4 &&
        CLUSTER_NAME=$(terraform output -raw gke_autopilot_name) &&
        INSTANCE_CONN_NAME=$(terraform output -raw instance_connection_name) &&
        printf 'PROJECT_ID=%s\nREGION=%s\nCLUSTER_NAME=%s\nINSTANCE_CONN_NAME=%s\n'
        "$PROJECT_ID" "$REGION" "$CLUSTER_NAME" "$INSTANCE_CONN_NAME" > /workspace/env.out &&
        echo 'Wrote /workspace/env.out:' &&
        cat /workspace/env.out

  # 1) Connect to cluster, fix namespace ownership, secrets, then helm install/upgrade
  - name: gcr.io/cloud-builders/gcloud
    id: kubectl-and-helm-deploy
    entrypoint: bash
    args:
      - -lc
      - >
        set -euo pipefail;
        source /workspace/env.out;
        echo "Using cluster: ${CLUSTER_NAME} in ${REGION}, project ${PROJECT_ID}";
        gcloud container clusters get-credentials "${CLUSTER_NAME}" --region "${REGION}" --project "${PROJECT_ID}";
        kubectl get ns vikunja >/dev/null 2>&1 || kubectl create ns vikunja;
        kubectl label ns vikunja app.kubernetes.io/managed-by=Helm --overwrite;
        kubectl annotate ns vikunja meta.helm.sh/release-name=vikunja --overwrite;
        kubectl annotate ns vikunja meta.helm.sh/release-namespace=vikunja --overwrite;
        DB_PASS=$(gcloud secrets versions access latest --secret=vikunja-db-password);
        kubectl -n vikunja create secret generic vikunja-db-secret --from-literal=POSTGRES_PASSWORD="${DB_PASS}" --dry-run=client -o yaml | kubectl apply -f -;
        kubectl -n vikunja create secret generic vikunja-app-secret --from-literal=DUMMY="ok" --dry-run=client -o yaml | kubectl apply -f -;
        helm repo add vikunja https://vikunja.github.io/helm-charts || true;
        helm repo update;
        helm upgrade --install vikunja vikunja/vikunja --namespace vikunja --wait --timeout 20m;
        kubectl -n vikunja get pods;
        kubectl -n vikunja get svc
