timeout: "1800s"
options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - id: "kubectl + helm deploy"
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -ceu
      - |
        set -o pipefail

        # Hard-coded since we removed trigger substitutions.
        PROJECT_ID="vikunja-case"
        REGION="europe-west4"
        CLUSTER_NAME="vikunja-autopilot"

        # Kubeconfig kept in /workspace (shared within this step).
        export KUBECONFIG=/workspace/kubeconfig

        echo "Fetching cluster credentials..."
        gcloud container clusters get-credentials "$CLUSTER_NAME" --region "$REGION" --project "$PROJECT_ID"

        echo "Ensure namespace exists and is Helm-adoptable..."
        kubectl get ns vikunja >/dev/null 2>&1 || kubectl create ns vikunja
        kubectl label ns vikunja app.kubernetes.io/managed-by=Helm --overwrite
        kubectl annotate ns vikunja meta.helm.sh/release-name=vikunja --overwrite
        kubectl annotate ns vikunja meta.helm.sh/release-namespace=vikunja --overwrite

        echo "Installing Helm 3..."
        curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

        echo "Deploying with Helm..."
        # Adjust path if your chart lives elsewhere.
        helm upgrade --install vikunja ./infra/helm \
          --namespace vikunja \
          --atomic --wait
