options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 0) Get kubeconfig for your cluster
  - name: gcr.io/cloud-builders/gcloud
    id: get-credentials
    entrypoint: bash
    args:
      - -ceu
      - |
        gcloud container clusters get-credentials vikunja-autopilot \
          --region europe-west4 \
          --project vikunja-case

  # 1) Ensure namespace exists and is Helm-adoptable
  - name: gcr.io/cloud-builders/gcloud
    id: prepare-namespace
    entrypoint: bash
    args:
      - -ceu
      - |
        kubectl get ns vikunja >/dev/null 2>&1 || kubectl create ns vikunja
        kubectl label ns vikunja app.kubernetes.io/managed-by=Helm --overwrite=true || true
        kubectl annotate ns vikunja meta.helm.sh/release-name=vikunja --overwrite=true || true
        kubectl annotate ns vikunja meta.helm.sh/release-namespace=vikunja --overwrite=true || true

  # 2) Helm deploy the local chart in ./helm
  - name: gcr.io/cloud-builders/gcloud
    id: helm-deploy
    entrypoint: bash
    args:
      - -ceu
      - |
        HELM_VERSION="v3.14.4"
        curl -sSL https://get.helm.sh/helm-$${HELM_VERSION}-linux-amd64.tar.gz | tar -xz
        mv linux-amd64/helm /usr/local/bin/helm
        helm version

        # Deploy (uses sqlite so the app starts without DB wiring)
        helm upgrade --install vikunja ./helm \
          -n vikunja \
          --wait --timeout 10m
