timeout: "1800s"
options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Use gcloud image (has bash + kubectl). Do everything in ONE step.
  - id: "kubectl + helm deploy"
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -ceu
      - |
        set -o pipefail

        # --- EDIT THESE 3 ONLY IF YOUR ENV DIFFERS ---
        PROJECT_ID="vikunja-case"
        REGION="europe-west4"
        CLUSTER_NAME="vikunja-autopilot"
        # ---------------------------------------------

        # Share kubeconfig via /workspace (always shared across steps; here we only have one step anyway)
        export KUBECONFIG=/workspace/kubeconfig

        echo "Fetching cluster credentials..."
        gcloud container clusters get-credentials "$CLUSTER_NAME" --region "$REGION" --project "$PROJECT_ID"

        echo "Ensure namespace exists and is Helm-adoptable..."
        kubectl get ns vikunja >/dev/null 2>&1 || kubectl create ns vikunja
        kubectl label ns vikunja app.kubernetes.io/managed-by=Helm --overwrite
        kubectl annotate ns vikunja meta.helm.sh/release-name=vikunja --overwrite
        kubectl annotate ns vikunja meta.helm.sh/release-namespace=vikunja --overwrite

        echo "Installing Helm 3 (local to this step)..."
        curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

        echo "Deploying with Helm (upgrade --install)..."
        # If you keep your chart in repo at ./infra/helm (recommended)
        helm upgrade --install vikunja ./infra/helm \
          --namespace vikunja \
          --atomic --wait

        # If instead you use a remote chart repo, comment the above and use something like:
        # helm repo add vikunja https://<your-helm-repo>
        # helm repo update
        # helm upgrade --install vikunja vikunja/vikunja -n vikunja --atomic --wait
