# Cloud Build pipeline: Terraform (GKE + Cloud SQL + secrets) -> Helm (Vikunja)
# Project: vikunja-case (717226960827)
# Region: europe-west4
timeout: "3600s"
options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 1) Terraform init/apply with GCS backend, then write outputs to /workspace/env.out
  - id: "terraform apply + outputs"
    name: "hashicorp/terraform:1.9.6"
    entrypoint: "bash"
    args:
      - -ceu
      - |
        # Static config (no Cloud Build substitutions)
        REGION="europe-west4"
        TFSTATE_BUCKET="vikunja-case-tfstate"
        # Build project from gcloud config
        PROJECT_ID="$(gcloud config get-value project 2>/dev/null)"

        cd infra/terraform

        terraform init -input=false \
          -backend-config="bucket=$TFSTATE_BUCKET" \
          -backend-config="prefix=vikunja/state"

        terraform apply -input=false -auto-approve \
          -var="project_id=$PROJECT_ID" \
          -var="region=$REGION"

        # Read outputs (fail fast if cluster name is missing)
        CLUSTER_NAME="$(terraform output -raw gke_autopilot_name)"
        INSTANCE_CONN_NAME="$(terraform output -raw instance_connection_name 2>/dev/null || true)"

        # Write an env file for later steps (only $VAR; no ${...})
        {
          echo "PROJECT_ID=$PROJECT_ID"
          echo "REGION=$REGION"
          echo "CLUSTER_NAME=$CLUSTER_NAME"
          if [ -n "$INSTANCE_CONN_NAME" ]; then
            echo "INSTANCE_CONN_NAME=$INSTANCE_CONN_NAME"
          fi
        } > /workspace/env.out
