steps:
  - name: gcr.io/cloud-builders/gcloud
    id: get-creds + prep namespace
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        CLUSTER_NAME="vikunja-autopilot"
        REGION="europe-west4"

        # Get kubeconfig
        gcloud container clusters get-credentials "$CLUSTER_NAME" --region "$REGION"

        # Persist kubeconfig for later steps
        export KUBECONFIG=/workspace/kubeconfig
        mkdir -p "$(dirname "$KUBECONFIG")"
        kubectl config view --raw > "$KUBECONFIG"

        # Ensure namespace exists and is Helm-adoptable (prevents the 'invalid ownership metadata' error)
        kubectl get ns vikunja >/dev/null 2>&1 || kubectl create ns vikunja
        kubectl label ns vikunja app.kubernetes.io/managed-by=Helm --overwrite
        kubectl annotate ns vikunja meta.helm.sh/release-name=vikunja --overwrite
        kubectl annotate ns vikunja meta.helm.sh/release-namespace=vikunja --overwrite

  - name: gcr.io/cloud-builders/helm:3.14.4
    id: helm upgrade/install
    env:
      - KUBECONFIG=/workspace/kubeconfig
    args:
      - upgrade
      - --install
      - vikunja
      - ./helm/vikunja
      - --namespace
      - vikunja
      - --create-namespace

options:
  # If your trigger sets a service account, this avoids the logs_bucket requirement.
  logging: CLOUD_LOGGING_ONLY
