# --- image & replicas ---
image:
  repository: vikunja/vikunja
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

# --- service ---
service:
  type: ClusterIP
  port: 80
  targetPort: 3456

# --- database (required by templates) ---
db:
  host: "34.147.70.155"   # <-- your Cloud SQL public IP
  port: 5432
  name: "vikunja"
  user: "vikunja"
  # DO NOT hardcode the password here; it will be injected from Secret Manager via --set at deploy time.
  # password: ""

# --- storage (required by pvc.yaml) ---
storage:
  enabled: true
  size: 10Gi
  # On GKE Autopilot the default SC is usually "standard-rwo" (check with: kubectl get sc)
  storageClassName: "standard-rwo"

# --- ingress (enable it) ---
ingress:
  enabled: true
  className: "gce"     # GKE's GLBC ingress class
  annotations: {}
  hosts:
    - host: "vikunja.example.com"    # <-- put your real domain here
      paths:
        - path: /
          pathType: Prefix
  tls: []  # add a managed cert later if you have one
