replicaCount: 1

api:
  image:
    repository: vikunja/api
    tag: "latest"
    pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3456

db:
  host: "34.147.70.155"          # your Cloud SQL public IP
  port: 5432
  name: "vikunja"
  user: "vikunja"
  # Tell the chart which Secret holds the password
  secretName: "vikunja-db-secret"
  secretKey: "postgresql-password"

storage:
  enabled: true
  size: 1Gi
  # storageClassName: ""         # optional

ingress:
  enabled: true
  className: "gce"
  annotations: {}
  hosts:
    - host: "vikunja.example.com"    # change to your DNS or keep placeholder
      paths:
        - path: /
          pathType: Prefix
  tls: []                             # add TLS when ready

# Define even if you don't use the proxy (chart references cloudsql.image)
cloudsql:
  enabled: false
  image: "gcr.io/cloud-sql-connectors/cloud-sql-proxy"
  tag: "2.11.3"
  instanceConnectionName: ""
  port: 5432

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
