image:
  repository: vikunja/vikunja
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 3456

# Add this block so templates/ingress.yaml can read .Values.ingress.enabled
ingress:
  enabled: false        # set true if you actually want an Ingress
  className: ""         # e.g. "gce" or "nginx" if you enable it
  annotations: {}       # add controller-specific annotations if needed
  hosts: []             # e.g. [{ host: "vikunja.example.com", paths: [{ path: "/", pathType: "Prefix" }] }]
  tls: []               # e.g. [{ hosts: ["vikunja.example.com"], secretName: "vikunja-tls" }]

# Add this block so templates/pvc.yaml can read .Values.storage.size
storage:
  enabled: true
  name: vikunja-data
  size: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""  # empty = cluster default; or set "standard-rwo" etc.

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
