# Images
image:
  api:
    repository: vikunja/api
    tag: "latest"
    pullPolicy: IfNotPresent
  frontend:
    repository: vikunja/frontend
    tag: "latest"
    pullPolicy: IfNotPresent

# Database (using Cloud SQL public IP you printed earlier)
db:
  host: "34.147.70.155"
  port: 5432
  name: "vikunja"
  user: "vikunja"
  passwordSecretName: "vikunja-db-secret"
  passwordSecretKey: "postgresql-password"

# Persistent storage for attachments
storage:
  size: "5Gi"
  storageClassName: "standard-rwo"

# Services
service:
  api:
    type: ClusterIP
    port: 3456
  frontend:
    type: ClusterIP
    port: 80

# Ingress (GCE)
ingress:
  enabled: true
  className: "gce"
  annotations: {}
  hosts:
    - host: ""        # leave empty for basic test; add domain later
      paths:
        - path: /
          pathType: Prefix

# Minimal requests to schedule smoothly on Autopilot
resources:
  api:
    requests:
      cpu: 150m
      memory: 256Mi
  frontend:
    requests:
      cpu: 100m
      memory: 128Mi
