image:
  repository: vikunja/vikunja
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 3456

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
