apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vikunja-files
  labels:
    app: vikunja
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.storageClassName | quote }}
  resources:
    requests:
      storage: {{ .Values.storage.size | quote }}
