{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vikunja
  namespace: vikunja
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - host: {{ .Values.ingress.host | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vikunja-frontend
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: vikunja-api
            port:
              number: 3456
{{- end }}